<a href="https://colab.research.google.com/github/mdaugherity/Numerical2024/blob/main/linear/Week_2_Linear_Systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Systems
PHYS 351, Dr. Daugherity


In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Lessons from last time

In [ ]:
x = 2
y = (2**0.5) * (2**0.5)
if x==y:
  print('EQUAL!')
else:
  print('NOT EQUAL?????!?  :(')

In [ ]:
x = 3.2
y = 2.6 + 0.2 + 0.2 + 0.2
x==y

NEVER EVER use == to see if 2 floating point numbers are equal!!!



In [ ]:
if np.abs(x-y)<1e-12:
  print('Close enough!')

In [ ]:
np.allclose(x,y,

Be very, very careful when subtracting 2 "big" numbers and getting a small one


In [ ]:
x = 1.23456789012345
y = 1.23456789012000
x-y  # this answer only has a few sig figs left

# The World's Simplest Math Problems

$y=mx+b$

But to do something more interesting, we could either do harder equations (we'll deal with *non*-linear later) or do lots of equations.

We'll need LINEAR ALGEBRA to do it!

# Linear Algebra 101

In [2]:
A = np.array([[1,2],[3,4]])
B = np.array([[0],[1]])
C = np.array([[-1,2]])
print(f"A = \n{A}\n")
print(f"B = \n{B}\n")
print(f"C = \n{C}")


A = 
[[1 2]
 [3 4]]

B = 
[[0]
 [1]]

C = 
[[-1  2]]


In [3]:
A+A

array([[2, 4],
       [6, 8]])

In [4]:
A+B

array([[1, 2],
       [4, 5]])

WARNING: python will sometimes GUESS and fill in numbers for illegal matrix operations!

In [5]:
D = np.array([[1,2,3],[4,5,6],[7,8,9]])
A+D

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [7]:
A.shape

(2, 2)

In [8]:
B.shape

(2, 1)

In [6]:
A*B  # using * makes python NOT do real matrix math

array([[0, 0],
       [3, 4]])

In [9]:
np.matmul(A,B)  # real matrix mult

array([[2],
       [4]])

In [10]:
A@B

array([[2],
       [4]])

In [11]:
B*A

array([[0, 0],
       [3, 4]])

In [12]:
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [13]:
B@C

array([[ 0,  0],
       [-1,  2]])

In [14]:
C@B

array([[2]])

## Identity, Inverse

In [15]:
A

array([[1, 2],
       [3, 4]])

In [16]:
np.eye(2)  # identity matrix

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.__version__

In [19]:
I = np.identity(2)

In [20]:
print(A@I)
print(I@A)
print(A)

[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]
[[1 2]
 [3 4]]


In [21]:
Ainv = np.linalg.inv(A)
print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [22]:
A@Ainv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [23]:
Ainv@A

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [24]:
A@Ainv==np.eye(2)

array([[ True,  True],
       [False, False]])

In [25]:
np.allclose(  Ainv@A, I)

True

In [26]:
A = np.array([[2,1],[-0.5,1]])
A

array([[ 2. ,  1. ],
       [-0.5,  1. ]])

In [27]:
b = np.array([[6],[1]])
b

array([[6],
       [1]])

In [28]:
# bad way
Ainv = np.linalg.inv(A)
print(Ainv)
x = Ainv@b
print("\nThe answer is ")
print(x)

[[ 0.4 -0.4]
 [ 0.2  0.8]]

The answer is 
[[2.]
 [2.]]


In [29]:
# easy, easy
x = np.linalg.solve(A,b)
print("\nThe answer is ")
print(x)


The answer is 
[[2.]
 [2.]]
